### ISSUE TITLE
Failure on mac

### ISSUE THREAD

**Issue by gerd2002** [servo/devices#24]
At least on macOS Sierra, this doesn't work with the following snippet:
```rust
extern crate device;

use device::bluetooth::{BluetoothAdapter, BluetoothDevice};

fn main() {

	let adapter = BluetoothAdapter::init().expect("No bluetooth adapter found!");
	println!("{:?}", adapter);

}
```
following backtrace:
```
hread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::begin_panic
             at libstd/panicking.rs:402
   5: std::panicking::try::do_call
             at libstd/panicking.rs:349
   6: std::panicking::try::do_call
             at libstd/panicking.rs:325
   7: <core::ops::range::Range<Idx> as core::fmt::Debug>::fmt
             at libcore/panicking.rs:72
   8: <core::ops::range::Range<Idx> as core::fmt::Debug>::fmt
             at libcore/panicking.rs:51
   9: <core::option::Option<T>>::unwrap
             at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:20
  10: blurmac::delegate::bm::delegate_class::{{closure}}
             at /Users/gs/.cargo/git/checkouts/devices-1d074a12853a87bb/1069d67/blurmac/src/delegate.rs:31
  11: std::sync::once::Once::call_once::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/sync/once.rs:227
  12: std::sync::once::Once::call_once::{{closure}}
             at libstd/sync/once.rs:340
  13: std::sync::once::Once::call_once
             at /Users/travis/build/rust-lang/rust/src/libstd/sync/once.rs:227
  14: blurmac::delegate::bm::delegate_class
             at /Users/gs/.cargo/git/checkouts/devices-1d074a12853a87bb/1069d67/blurmac/src/delegate.rs:29
  15: blurmac::delegate::bm::delegate
             at /Users/gs/.cargo/git/checkouts/devices-1d074a12853a87bb/1069d67/blurmac/src/delegate.rs:219
  16: <core::cell::UnsafeCell<T>>::new
             at /Users/gs/.cargo/git/checkouts/devices-1d074a12853a87bb/1069d67/blurmac/src/adapter.rs:31
  17: <alloc::arc::Arc<T> as core::ops::drop::Drop>::drop
             at /Users/gs/.cargo/git/checkouts/devices-1d074a12853a87bb/1069d67/src/bluetooth.rs:256
  18: encore::main
             at src/main.rs:10
  19: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  20: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  21: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:102
  22: rust_panic
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  23: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  24: encore::main
```

**Comment by LegNeato** [comment]
`Protocol::get("CBCentralManagerDelegate")` seems to be returning `None`

**Comment by gerd2002** [comment]
Could one of the main contributors (mentioning @dati91) look at this?

**Comment by dati91** [comment]
@gerd2002 Hi, sorry but I don't have access to mac machine at the moment.
But let me just ping the original author, maybe he can help out. @akosthekiss

**Comment by LegNeato** [comment]
FWIW I did a bit of debugging but am lost on how to keep going. I used `otool` and can see that `IOBluetooth` and `CoreBluetooth` are linked in the lib (I think I did it correctly). Also, `Protocol::get("NSObject")` works.

**Comment by LegNeato** [comment]
Any ideas I can use to help debug @akosthekiss?

**Comment by LegNeato** [comment]
@akosthekiss?

**Comment by dati91** [comment]
@LegNeato try [this](https://gist.github.com/dati91/47975018d5d84767cccf0a9b6e38b018)
this will include some mac specific libs that might be missing

**Comment by gerd2002** [comment]
@dati91 amazing, that fixed it!
